AWSTemplateFormatVersion: "2010-09-09"
Description: "GuardDuty detector for organization member accounts"
Parameters:
  FindingPublishingFrequency:
    Type: String
    Default: FIFTEEN_MINUTES
    AllowedValues:
      - FIFTEEN_MINUTES
      - ONE_HOUR
      - SIX_HOURS
Resources:
  Detector:
    Type: AWS::GuardDuty::Detector
    Properties:
      Enable: true
      FindingPublishingFrequency: !Ref FindingPublishingFrequency
